### ISSUE TITLE
MW4530R安装正常，无法运行

### ISSUE THREAD

**Issue by xuexiaokang** [hikaruchang/BonusCloud-Node#2]
主机名        MW4530R
主机型号        Mercury MW4530R v1
固件版本        Openwrt 2U4U-R5 / LuCI lede-17.01 branch (git-18.201.27126-7bf0367)
主控芯片        Atheros AR9344 rev 2
构架        MIPS 74Kc V4.12
内核版本        4.4.153

安装bonuscloud_0.2.2-5o-1_mips_24kc.ipk正常，运行了一会，界面就显示BonusCloud is Not Running

**Comment by HikaruChang** [comment]
升级6o
