### ISSUE TITLE
newifi3 D2，官方固件，安装失败

### ISSUE THREAD

**Issue by piqihaha** [hikaruchang/BonusCloud-Node#3]
newifi3 D2，官方固件，安装失败。有没有类似绿色免安装的程序呢？直接shell运行，新3的官方固件，LUI界面好像不支持
-------------------
[root@newifi_723D:/root]#cat /proc/version
Linux version 3.14.79 (lea@server.pbr.link) (gcc version 4.8.3 (PandoraBox/Linaro GCC 4.8-2014.04 2018-02-01-git-80fcf99) ) #12 SMP Mon Jun 11 14:19:45 CST 2018
[root@newifi_723D:/root]#
---------------------------------------
[root@newifi_723D:/root]#opkg install bonuscloud_0.2.2-5o-1_mipsel_24kec_dsp.ipk
Installing bonuscloud (0.2.2-5o-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for bonuscloud:
 *      libssp *        luci-lib-jsonc *        liblzo *        libltdl *
 * opkg_install_cmd: Cannot install package bonuscloud.

**Comment by HikaruChang** [comment]
你用官方定制固件100%安装不上

**Comment by piqihaha** [comment]
有没有这种可能性，绿色版，不是ipk安装包，需要什么插件直接打包的呢

**Comment by HikaruChang** [comment]
没有可能，需要依赖和驱动

**Comment by piqihaha** [comment]
curl wget ca-bundle ca-certificates liblzo ip6tables-extra kmod-ip6tables-extra   是不是这几个依赖包装了就可以了？
