### ISSUE TITLE
为什么我的rt-ac66u不能安装？？

### ISSUE THREAD

**Issue by Potterli20** [hikaruchang/BonusCloud-Node#4]
为什么我的rt-ac66u不能安装？？不是rt-ac66-b1哦，是rt-ac66u 固件是http://firmware.koolshare.cn/Koolshare_Merlin_Legacy_380/ASUS/RT-AC66U/X7.6/

**Comment by Potterli20** [comment]
potter@RT-AC66U-3DC8:/tmp/mnt/sda1/ftp# opkg install bonuscloud_0.2.2-8o-1_mips_
24kc.ipk 
Installing bonuscloud (0.2.2-8o-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for bonuscloud:
 * 	luci-lib-jsonc * 	ip6tables * 	kmod-tun * 
 * opkg_install_cmd: Cannot install package bonuscloud.

**Comment by HikaruChang** [comment]
缺这些依赖，你得自己装上，另外，仅支持OpenWrt谢谢，请认真看说明。
